site_name: IST659

theme:
  name: material
  icon:
    logo: material/database
  palette: 
    scheme: slate
    primary: deep orange
    accent: indigo


extra:
  version:
    provider: mike  


plugins:
  - search:
      lang: en


repo_url: https://github.com/squidfunk/mkdocs-material